### ISSUE TITLE
Unknown type for bencode

### ISSUE THREAD

**Issue by Yuuki2012** [effigies/BitTornado#25]
```Python
TypeError: Unknown type for bencode: <class 'float'>
Traceback (most recent call last):
  File "/home/BitTornado/BitTornado/Network/RawServer.py", line 109, in listen_forever
    func()
  File "/home/BitTornado/BitTornado/Tracker/track.py", line 1104, in save_state
    self.state.write(self.dfile)
  File "/home/BitTornado/BitTornado/Meta/bencode.py", line 194, in write
    handle.write(bencode(self))
  File "/home/BitTornado/BitTornado/Meta/bencode.py", line 36, in __call__
    self.encode(data, ctext)
  File "/home/BitTornado/BitTornado/Meta/bencode.py", line 60, in encode
    self.encode(data, ctext)
  File "/home/BitTornado/BitTornado/Meta/bencode.py", line 60, in encode
    self.encode(data, ctext)
  File "/home/BitTornado/BitTornado/Meta/bencode.py", line 46, in encode
    self.encode(element, ctext)
  File "/home/BitTornado/BitTornado/Meta/bencode.py", line 46, in encode
    self.encode(element, ctext)
  File "/home/BitTornado/BitTornado/Meta/bencode.py", line 73, in encode
    raise TypeError('Unknown type for bencode: ' + str(type(data)))
```

I keep getting this, I don't know why, I have 2 torrents in my folder but neither are seeding or being leeched, this just occurs randomly and crashes the tracker, any idea?

I'm using the following cmd btw: ./bttrack.py --port 65000 --dfile dstate --allow_get 1 --allowed_dir ./torrents/ --infopage_redirect "MY_SITE_HERE" --logfile ./logs/log.txt

**Comment by effigies** [comment]
Thanks for the report. (I updated your comment because the type was invisible.)

Looks like file `mtime`s are `float`s, which can't be `bencode`d. The simplest solution will be to coerce the types to `int`, but I'll need to decide whether it's better to do that when writing to file or when reading the `mtime`s in the first place. From a quick glance, BitTornado doesn't actually use the `mtime`, so it probably doesn't matter, but I'll want to look a little closer before breaking something.

**Comment by effigies** [comment]
Can you verify that the issue_25 branch solves your problem?

**Comment by effigies** [comment]
I was able to produce the error by hitting Control-C, forcing it to save the state file and close. And the default save interval is 300s (5min).

**Comment by Yuuki2012** [comment]
Is that the same error? (I didn't really check that, thought it was normal because I'm forcing it to close, happens with a lot of programs), sometimes it happens and sometimes it doesn't.

**Comment by effigies** [comment]
Yeah. It goes through `Tracker.save_state`, which is called [at](https://github.com/effigies/BitTornado/blob/master/BitTornado/Tracker/track.py#L354) [intervals](https://github.com/effigies/BitTornado/blob/master/BitTornado/Tracker/track.py#L1103) and [at shutdown](https://github.com/effigies/BitTornado/blob/master/BitTornado/Tracker/track.py#L1208).

In general, tracebacks are a bad sign. If you encounter them when exiting any BitTornado programs, feel free to start another issue.

**Comment by Yuuki2012** [comment]
Well I just use the tracker, so can't really tell. Atm I have no need for the other programs ^^

**Comment by effigies** [comment]
How'd your tests go?

**Comment by Yuuki2012** [comment]
Haven't gotten any errors until now, I restarted it a few times (force closing with CTRL+C) but it saved the dstate file just fine, so I think it's fixed now?

**Comment by effigies** [comment]
Sounds good. Merging.
