### ISSUE TITLE
AttributeError: 'NatCheck' object has no attribute 'bufferlen'

### ISSUE THREAD

**Issue by Yuuki2012** [effigies/BitTornado#27]
Got an error again, unrelated to the previous issue:

> Traceback (most recent call last):
  File "/home/BitTornado/BitTornado/Network/RawServer.py", line 120, in listen_forever
    self.sockethandler.handle_events(events)
  File "/home/BitTornado/BitTornado/Network/SocketHandler.py", line 293, in handle_events
    s.handler.data_came_in(s, data)
  File "/home/BitTornado/BitTornado/Network/NatCheck.py", line 161, in data_came_in
    self.read(s)
  File "/home/BitTornado/BitTornado/Network/NatCheck.py", line 197, in _read
    if self.bufferlen is not None:
AttributeError: 'NatCheck' object has no attribute 'bufferlen'

As of now, the Tracker hasn't crashed yet, so I don't see a problem with it... Just thought I'd mention it.

Edit: Okay the tracker crashes now by spamming the error into console. (to reproduce this error (for me at least); Put a torrent in the torrents directory and 'Update Trackers' on ruTorrent (not sure if it is also the case with other clients))

**Comment by effigies** [comment]
Thanks for the report. Didn't take long to track down, and I think we can safely remove that branch, as the function it would call also doesn't exist. Opened #28, if you want to verify that it doesn't cause new bugs.

**Comment by Yuuki2012** [comment]
I'll check when I'm back on my PC.

**Comment by Yuuki2012** [comment]
Ok, I'm not getting the error anymore when Force Updating the tracker on my client(s), so I think you can merge it.

**Comment by effigies** [comment]
Got it. Pushed a new commit.

**Comment by Yuuki2012** [comment]
Haven't gotten any errors for ~15min, if anything pops up I'll poke you again ;)
