### ISSUE TITLE
Doesn't build ...

### ISSUE THREAD

**Issue by Schimmelreiter** [effigies/BitTornado#3]
I've tried a myriad of combinations of Python 2.6, Python 2.7, Python 3.4 (With the python3 branch of course), various wxPython versions, py2exe and none of them can build a working BitTornado on Windows.

The basic problem:
Either I get missing _sysconfigdata, missing psyco (Which is dead and isn't available for anything but Python 2.6 and older), missing win32com.gen.py ...

Can you provide a list of components required to actually build BitTornado, incl. their respective versions?

Or maybe you could even provide a binary somewhere :)

**Comment by effigies** [comment]
Closing. Please reopen if you're still having trouble.
