### ISSUE TITLE
how can the btmakemetafile.py support filename include Chinese ?

### ISSUE THREAD

**Issue by yang502** [effigies/BitTornado#42]
I am using the branch on  Python2.7 .
# BitTornado/btmakemetafile.py   http:172.21.108.66:6969/announce /opt/yang/iso/win7高中模板.base 
error: bad filename: win7高中模板.base
run with no args for parameter explanations
How can the makebt file  can  support filename include  Chinese?

**Comment by effigies** [comment]
It should support unicode filenames. I can try to fix this, though for the most part I'm not working on 2.7 anymore. Can you open a Python shell and give the output of:

```Python
import sys
print sys.getfilesystemencoding()
```

**Comment by effigies** [comment]
Can you check out the `encoding_fix` branch? If that doesn't fix it, it should at least get us closer to understanding the problem.

**Comment by WuYiP** [comment]
Hello,effigies, I tried the way you told ,but  it didn't fix it in the encoding_fix branch .

**Comment by WuYiP** [comment]
Thank you ,effigies,I was also confused about the problem before.Now,because of you ,I can solve it .

**Comment by yang502** [comment]
in the python(2.7) prompt ,the unicode is UTF-8.
I haved tried the encoding_fix ,it has works well with filename include Chinese.
Hope it will also works in python2.7 branch master branch !
Thanks!

**Comment by effigies** [comment]
Great! Glad to hear it got fixed. Merged, so the python2.7 should be working for you.
